Securonauts/discourse_reports

assets/javascripts/discourse/controllers/topic.js.es6
assets/javascripts/discourse/dialects/navigation_bbcode.js
assets/javascripts/discourse/templates/post-book.hbs
assets/javascripts/discourse/templates/topic-book.hbs
assets/javascripts/discourse/views/post_view.js.es6
assets/stylesheets/books.css.scss
assets/stylesheets/comments.css.scss
assets/stylesheets/navigation.css.scss
config/locales/client.en.yml

https://www.pivotaltracker.com/story/show/85590382

Section view fixes

---

assets/javascripts/discourse/dialects/part_bbcode.js
assets/stylesheets/part.css.scss
plugin.rb

https://www.pivotaltracker.com/story/show/85503094

Add [chapter] and [sections] tags

---

docs/heroku-deploy.md

https://www.pivotaltracker.com/story/show/86092218

[#86092218] Add base documentation describing heroku deployment process

---

assets/javascripts/discourse/dialects/part_bbcode.js

https://www.pivotaltracker.com/story/show/85503094

[#85503094] Add ability to use headings in [chapter] tag

---

assets/javascripts/discourse/dialects/part_bbcode.js

https://www.pivotaltracker.com/story/show/86189608

[#86189608] Add part tag

---

assets/javascripts/discourse/templates/topic-part.hbs

https://www.pivotaltracker.com/story/show/85996958

[#85996958] Remove replyes panel from part view

---

assets/javascripts/discourse/controllers/topic.js.es6
assets/javascripts/discourse/templates/topic-book.hbs

https://www.pivotaltracker.com/story/show/85997218

Remove additional comments panel if does not exist comments

---

assets/stylesheets/part.css.scss

https://www.pivotaltracker.com/story/show/85886872

[#85886872] HTML/CSS for an updated Part view

---

assets/javascripts/discourse/templates/topic-part.hbs

https://www.pivotaltracker.com/story/show/85996948
https://www.pivotaltracker.com/story/show/85997102

Remove suggested posts and statistic panel from Part view

---

assets/javascripts/discourse/templates/topic-part.hbs

https://www.pivotaltracker.com/story/show/85996382

[#85996382] Remove global notice form part view

---

assets/javascripts/discourse/templates/post-part.hbs
assets/javascripts/discourse/views/post-part-menu.js.es6
assets/stylesheets/books.css.scss
plugin.rb

https://www.pivotaltracker.com/story/show/85996930

[#85996930] Remove unused buttons from option panel

---

assets/javascripts/discourse/templates/post-part.hbs

https://www.pivotaltracker.com/story/show/85996546

[#85996546] Remove reply as linked topic and avatar from part view

---

assets/javascripts/discourse/templates/post-part.hbs
assets/javascripts/discourse/templates/topic-part.hbs
assets/stylesheets/part.css.scss

https://www.pivotaltracker.com/story/show/86190140

[#86190140] TOC screen mark up

---

assets/javascripts/discourse/templates/topic-book.hbs
assets/javascripts/discourse/templates/topic-part.hbs

https://www.pivotaltracker.com/story/show/86365098

[#86365098] Remove option to edit topic title

---

assets/javascripts/discourse/templates/topic-part.hbs

https://www.pivotaltracker.com/story/show/86314310

[#86314310] Remove quote reply pop-up button for part and TOC view

---

assets/javascripts/discourse/controllers/topic.js.es6

https://www.pivotaltracker.com/story/show/86313588

Do not show invalid comments on the stream until post

---

assets/stylesheets/navigation.css.scss

https://www.pivotaltracker.com/story/show/86313672

[#86313672] Navigation links mark up adjustment

---

assets/javascripts/discourse/controllers/topic.js.es6
assets/javascripts/discourse/mixins/archetype-template.js.es6
assets/javascripts/discourse/models/topic.js.es6
assets/javascripts/discourse/templates/topic-admin-menu.hbs
assets/javascripts/discourse/templates/topic-part.hbs
config/locales/client.en.yml
config/locales/server.en.yml
plugin.rb

https://www.pivotaltracker.com/story/show/86365152

[#86365152] Add ability to set Topic as a TOC

---

assets/stylesheets/comments.css.scss

https://www.pivotaltracker.com/story/show/86421032

[#86421032] Section Quote reply post background adjustment

---

assets/stylesheets/comments.css.scss

https://www.pivotaltracker.com/story/show/86421032

[#86421032] Fix avatars alignment when comment is minimal size

---

assets/javascripts/discourse/helpers/current-year.js.es6
assets/javascripts/discourse/templates/footer.hbs
assets/stylesheets/footer.css.scss
plugin.rb

https://www.pivotaltracker.com/story/show/86504046

[#86504046] Add bottom navigation bar

---

assets/javascripts/discourse/templates/homepage.hbs
assets/stylesheets/views/landing.css.scss

https://www.pivotaltracker.com/story/show/86682854

[#86682854] Remove the image from first panel on Homepage

---

assets/stylesheets/navigation.css.scss

https://www.pivotaltracker.com/story/show/86983104

[#86983104] Set navigation bar background on Section view

---

assets/javascripts/discourse/templates/header.hbs
assets/stylesheets/header.css.scss

https://www.pivotaltracker.com/story/show/86806868

Get search feature back

---

spec/controllers/discourse_reports/homepage_controller_spec.rb
spec/serializers/discourse_reports/topic_homepage_serializer_spec.rb

https://www.pivotaltracker.com/story/show/86597794

[#86597794] Add rspec tests for homepage

---

assets/javascripts/discourse/routes/application.js.es6
assets/javascripts/discourse/routes/signup.js.es6
assets/javascripts/discourse/templates/header.hbs
assets/javascripts/discourse/templates/signup.hbs
assets/javascripts/discourse/views/signup.js.es6
config/locales/client.en.yml
plugin.rb

https://www.pivotaltracker.com/story/show/86353718

[#86353718] Build create account page

---

assets/javascripts/discourse/routes/application.js.es6
assets/javascripts/discourse/routes/login.js.es6
assets/javascripts/discourse/templates/header.hbs
assets/javascripts/discourse/templates/login.hbs
assets/javascripts/discourse/views/login.js.es6
plugin.rb

https://www.pivotaltracker.com/story/show/86353646

[#86353646] Add login template

---

assets/javascripts/discourse/templates/components/user-fields/text.hbs
assets/javascripts/discourse/templates/signup.hbs
assets/stylesheets/views/landing.css.scss
assets/stylesheets/views/signup.css.scss
config/locales/client.en.yml
plugin.rb

https://www.pivotaltracker.com/story/show/86788644

Create account page custom view

---

assets/javascripts/discourse/templates/login.hbs
assets/javascripts/discourse/templates/signup.hbs
assets/stylesheets/views/login.css.scss
assets/stylesheets/views/signup.css.scss
config/locales/client.en.yml
plugin.rb

https://www.pivotaltracker.com/story/show/86788632

[#86788632] Login Page mark up

---

assets/javascripts/discourse/templates/user/user.hbs
config/locales/client.en.yml
plugin.rb

https://www.pivotaltracker.com/story/show/87114136

[#87114136] Add navigation for profile page

---

assets/javascripts/discourse/templates/login.hbs

https://www.pivotaltracker.com/story/show/87310084

[#87310084] Login page: loading spinner position is a bit off

---

assets/javascripts/discourse/routes/app-route-map.js.es6
assets/javascripts/discourse/templates/user/notifications.hbs
assets/javascripts/discourse/templates/user/recipes.hbs
assets/javascripts/discourse/templates/user/user.hbs
plugin.rb

https://www.pivotaltracker.com/story/show/87310404

[#87310404] Add comming soon templates for recipes and notifications pages

---

assets/javascripts/initializers/disable-ubuntu.js.es6

https://www.pivotaltracker.com/story/show/87481738

[#87481738] Remove ubuntu login

---

assets/javascripts/discourse/templates/login.hbs
assets/stylesheets/views/login.css.scss
config/locales/client.en.yml

https://www.pivotaltracker.com/story/show/87481718

[#87481718] Change Login page text

---

assets/javascripts/discourse/templates/header.hbs

https://www.pivotaltracker.com/story/show/87481094
https://www.pivotaltracker.com/story/show/87481226

Add social links

---

app/controllers/discourse_reports/homepages_controller.rb
app/serializers/discourse_reports/homepage_serializer.rb
app/serializers/discourse_reports/topic_homepage_serializer.rb
assets/javascripts/discourse/templates/homepage.hbs
assets/stylesheets/views/landing.css.scss
config/settings.yml
plugin.rb

https://www.pivotaltracker.com/story/show/87057928

[#87057928] Add top viewed topics at homepage

---

assets/javascripts/discourse/templates/homepage.hbs
assets/stylesheets/views/landing.css.scss

https://www.pivotaltracker.com/story/show/87057928

[#87057928] Fix content dependencies

---

config/locales/server.en.yml
config/settings.yml

https://www.pivotaltracker.com/story/show/86903002
Update Discourse site settings for Stackoverflow authorization.

[#86903002] Add discourse settings for StackExchange

---

assets/javascripts/discourse/dialects/part_bbcode.js
assets/stylesheets/part.css.scss
assets/stylesheets/views/toc.css.scss

https://www.pivotaltracker.com/story/show/87059006

[#87059006] Reformat TOC to match updated wireframe

---

assets/javascripts/discourse/templates/about-dropdown.hbs
assets/javascripts/discourse/templates/discussions-dropdown.hbs
assets/javascripts/discourse/templates/header.hbs
assets/javascripts/discourse/templates/help-dropdown.hbs
assets/javascripts/discourse/templates/resources-dropdown.hbs
config/locales/client.en.yml

https://www.pivotaltracker.com/story/show/87058032

Update dropdowm options

---

assets/javascripts/discourse/routes/app-route-map.js.es6
assets/javascripts/discourse/templates/footer.hbs
assets/javascripts/discourse/templates/static-page.hbs
assets/javascripts/discourse/templates/terms-of-use.hbs
assets/javascripts/discourse/views/terms-of-use.js.es6
assets/stylesheets/views/static.css.scss
config/locales/client.en.yml
config/routes.rb
plugin.rb

https://www.pivotaltracker.com/story/show/87481002

[#87481002] Created terms of use page

---

assets/javascripts/discourse/routes/app-route-map.js.es6
assets/javascripts/discourse/templates/footer.hbs
assets/javascripts/discourse/templates/privacy-policy.hbs
assets/javascripts/discourse/views/privacy-policy.js.es6
config/locales/client.en.yml
config/routes.rb

https://sourceclear.atlassian.net/browse/FLAT-31

Privacy Policy page created

---

assets/javascripts/discourse/routes/app-route-map.js.es6
assets/javascripts/discourse/templates/contributors.hbs
assets/javascripts/discourse/templates/help-dropdown.hbs
assets/javascripts/discourse/views/contributors.js.es6
config/locales/client.en.yml
config/routes.rb

https://sourceclear.atlassian.net/browse/FLAT-9

Contributors page created

---

assets/javascripts/discourse/routes/app-route-map.js.es6
assets/javascripts/discourse/templates/communities.hbs
assets/javascripts/discourse/templates/homepage.hbs
assets/javascripts/discourse/views/communities.js.es6
assets/javascripts/initializers/discourse_reports.js.es6
config/locales/client.en.yml
config/routes.rb
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-8

Communities page created

---

assets/javascripts/discourse/routes/app-route-map.js.es6
assets/javascripts/discourse/templates/contact.hbs
assets/javascripts/discourse/templates/footer.hbs
assets/javascripts/discourse/views/contact.js.es6
assets/javascripts/initializers/discourse_reports.js.es6
config/locales/client.en.yml
config/routes.rb
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-30

Contact page created

---

assets/javascripts/discourse/routes/app-route-map.js.es6
assets/javascripts/discourse/templates/about-site.hbs
assets/javascripts/discourse/templates/help-dropdown.hbs
assets/javascripts/discourse/views/about-site.js.es6
assets/javascripts/initializers/discourse_reports.js.es6
config/locales/client.en.yml
config/routes.rb
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-7

About page created

---

app/controllers/discourse_reports/homepages_controller.rb

https://sourceclear.atlassian.net/secure/RapidBoard.jspa?rapidView=10&view=planning&selectedIssue=FLAT-2

Change top topics on homepage

---

app/controllers/discourse_reports/homepages_controller.rb

https://sourceclear.atlassian.net/browse/FLAT-24

Fix redirect to login page for unauthenticated users

---

app/models/topic.rb
app/serializers/topic_view_serializer.rb
assets/javascripts/discourse/models/composer.js.es6
assets/javascripts/discourse/templates/composer.hbs
assets/stylesheets/sections.css.scss
config/locales/client.en.yml
lib/post_revisor.rb
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-40

Add position input field into topic section FLAT-40

---

app/controllers/discourse_reports/admin/chapters_controller.rb
app/controllers/discourse_reports/admin/parts_controller.rb
app/models/discourse_reports/part.rb
app/serializers/discourse_reports/chapter_serializer.rb
app/serializers/discourse_reports/part_serializer.rb
assets/javascripts/admin/controllers/admin-chapter.js.es6
assets/javascripts/admin/controllers/admin-part.js.es6
assets/javascripts/admin/controllers/admin-toc.js.es6
assets/javascripts/admin/models/chapter.js.es6
assets/javascripts/admin/models/part.js.es6
assets/javascripts/admin/templates/toc.hbs
assets/javascripts/admin/views/admin-chapter.js.es6
assets/javascripts/initializers/discourse_reports.js.es6
config/locales/client.en.yml
config/routes.rb
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-38

[#FLAT-38] Admin chapter feature

---

app/controllers/discourse_reports/admin/parts_controller.rb
assets/javascripts/admin/templates/toc.hbs
assets/stylesheets/admin/toc.css.scss
assets/stylesheets/part.css.scss
assets/stylesheets/views/toc.css.scss
config/locales/client.en.yml
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-57

57 admin toc panel ui

---

app/controllers/discourse_reports/table_contents_controller.rb
app/controllers/discourse_reports/topics_controller.rb
assets/javascripts/discourse/routes/app-route-map.js.es6
assets/javascripts/discourse/routes/table-of-contents.js.es6
assets/javascripts/initializers/discourse_reports.js.es6
config/routes.rb
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-68

[FLAT 68] Add table-of-contents route

---

assets/javascripts/discourse/templates/communities-dropdown.hbs
config/locales/client.en.yml

https://sourceclear.atlassian.net/browse/FLAT-75

[flat-75] Add events navigation item

---

assets/javascripts/discourse/templates/communities-dropdown.hbs
config/locales/client.en.yml

https://sourceclear.atlassian.net/browse/FLAT-83

[flat-83] Request a community menu option

---

assets/javascripts/discourse/templates/help-dropdown.hbs
config/locales/client.en.yml

https://sourceclear.atlassian.net/browse/FLAT-84

[flat-84] Create an FAQ menu option

---

app/controllers/discourse_reports/table_contents_controller.rb
app/models/topic.rb
app/services/discourse_reports/generate_table_content.rb
db/migrate/20150225131740_change_topics_position_default_value.rb

https://sourceclear.atlassian.net/browse/FLAT-74

[#FLAT-74] Fix toc ordering

---

assets/javascripts/discourse/templates/supporters.hbs
assets/stylesheets/views/static.css.scss

https://sourceclear.atlassian.net/browse/FLAT-82

[flat-82] create supporters page layout

---

config/locales/client.en.yml

https://sourceclear.atlassian.net/browse/FLAT-93

[flat-93] Change link title - About the site

---

assets/javascripts/discourse/templates/login.hbs
config/locales/client.en.yml

https://sourceclear.atlassian.net/browse/FLAT-90

Update content on login page flat 90

---

assets/javascripts/discourse/templates/modal/forgot_password.hbs
config/locales/client.en.yml
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-91

[#FLAT-91] Update forgot password modal window text

---

assets/javascripts/discourse/templates/help-dropdown.hbs
config/locales/client.en.yml

https://sourceclear.atlassian.net/browse/FLAT-94

[flat-94] Remove "Contributors" menu option

---

assets/javascripts/discourse/templates/community-request.hbs
config/locales/client.en.yml

https://sourceclear.atlassian.net/browse/FLAT-99

[flat-99] Content updates on Request a community page

---

assets/javascripts/discourse/templates/communities/about.hbs

https://sourceclear.atlassian.net/browse/FLAT-96

[flat-96] Remove line-breaks from "About Communities" text

---

app/controllers/discourse_reports/table_contents_controller.rb
app/models/topic.rb
app/services/discourse_reports/generate_navigation_links.rb

https://sourceclear.atlassian.net/browse/FLAT-67

[FLAT-67] Navigation links

---

assets/javascripts/discourse/controllers/quote-button.js.es6
assets/javascripts/discourse/views/post-section-menu.js.es6
assets/stylesheets/sections.css.scss

https://sourceclear.atlassian.net/browse/FLAT-72

[#FLAT-72] Remove reply buttons for book sections

---

assets/javascripts/discourse/models/composer.js.es6
assets/javascripts/discourse/templates/composer.hbs

https://sourceclear.atlassian.net/browse/FLAT-97

[#FLAT-97] Add ability to save section topic without setting a chapter

---

assets/javascripts/discourse/controllers/quote-button.js.es6
assets/javascripts/discourse/mixins/reply-settings.js.es6
assets/javascripts/discourse/views/post-section-menu.js.es6
config/locales/server.en.yml
config/settings.yml
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-72

[#FLAT-72] Add checkbox to disable replies to admin menu

---

app/controllers/application_controller.rb
config/initializers/secure_headers.rb
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-58

[#FLAT-58] Install secure headers gem

---

assets/javascripts/discourse/routes/about-site.js.es6
assets/javascripts/discourse/routes/communities.js.es6
assets/javascripts/discourse/routes/community-request.js.es6
assets/javascripts/discourse/routes/contact.js.es6
assets/javascripts/discourse/routes/faq.js.es6
assets/javascripts/discourse/routes/privacy-policy.js.es6
assets/javascripts/discourse/routes/supporters.js.es6
assets/javascripts/discourse/routes/terms-of-use.js.es6
assets/javascripts/initializers/discourse_reports.js.es6
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-107

[#107] Redirect to login page if required

---

app/models/topic.rb

it was impossible to add plugin to project and start migrations before this fix

skip topic.position using until it's added to table schema

---

app/mailers/invite_mailer.rb
config/locales/server.en.yml
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-80

[#FLAT-80] Add invitation email to admin interface

---

assets/javascripts/discourse/routes/login.js.es6

https://sourceclear.atlassian.net/browse/FLAT-106

[#FLAT-106] Fix login route

---

assets/javascripts/discourse/templates/header.hbs
assets/stylesheets/header.css.scss

https://sourceclear.atlassian.net/browse/FLAT-118
* Move Discourse "hamburger" menu to the right of the profile image/avatar
* Fix top bar icons alignment

[FLAT-118] Move Discourse "hamburger" menu to the right of the profile image/avatar

---

assets/stylesheets/views/toc.css.scss

https://sourceclear.atlassian.net/browse/FLAT-125

[FLAT-125] TOC layout: add padding above Part header, and between rows of sections

---

app/controllers/discourse_reports/static_contents_controller.rb
assets/javascripts/discourse/routes/login.js.es6
assets/javascripts/discourse/templates/login.hbs
config/locales/client.en.yml
config/locales/server.en.yml
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-138

[#FLAT-138] Expose login page text in admin

---

app/controllers/discourse_reports/static_contents_controller.rb
assets/javascripts/discourse/routes/community-request.js.es6
assets/javascripts/discourse/templates/community-request.hbs
config/locales/client.en.yml
config/locales/server.en.yml
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-136

[#FLAT-136] Expose request community in admin interface

---

assets/stylesheets/navigation.css.scss

https://sourceclear.atlassian.net/browse/FLAT-117

[FLAT-117] Remove padding above Category tabs

---

assets/javascripts/discourse/models/composer.js.es6
assets/javascripts/discourse/templates/composer.hbs
assets/javascripts/initializers/composer-fields.js.es6

https://sourceclear.atlassian.net/browse/FLAT-12

[#FLAT-12] Fix plugin to properly work with Tagger

---

app/mailers/invite_mailer.rb
config/locales/server.en.yml

https://sourceclear.atlassian.net/browse/FLAT-145

[#FLAT-145] Change invitation email title

---

README.md

https://sourceclear.atlassian.net/browse/FLAT-141

[#FLAT-141] Update installation instructions

---

assets/javascripts/discourse/templates/header.hbs

https://sourceclear.atlassian.net/browse/FLAT-160

[#FLAT-160] Change Twitter link

---

assets/javascripts/discourse/templates/about-site.hbs
assets/stylesheets/views/static.css.scss
config/locales/client.en.yml

https://sourceclear.atlassian.net/browse/FLAT-163

[FLAT-163] Update "About page"

---

app/serializers/current_user_serializer.rb
assets/javascripts/discourse/controllers/recipe-form.js.es6
assets/javascripts/discourse/templates/navigation/category.hbs
assets/javascripts/discourse/templates/recipes.hbs
assets/stylesheets/views/recipes.css.scss
config/locales/server.en.yml
config/routes.rb
lib/recipe_constraint.rb
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-133

[#FLAT-133] Recipe trust level

---

assets/javascripts/discourse/templates/user/user.hbs

https://sourceclear.atlassian.net/browse/FLAT-171

[#flat-171] Fix recipes config in profile tab

---

assets/javascripts/discourse/controllers/topic.js.es6
assets/javascripts/discourse/mixins/archetype-template.js.es6
assets/javascripts/discourse/models/topic.js.es6
assets/javascripts/discourse/templates/post-blog.hbs
assets/javascripts/discourse/templates/topic-admin-menu.hbs
assets/javascripts/discourse/templates/topic-blog.hbs
config/locales/client.en.yml
config/locales/server.en.yml
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-169

[#FLAT-169] Add Blog archetype

---

assets/stylesheets/base/base.css.scss

https://sourceclear.atlassian.net/browse/FLAT-172

[#172] CSS style for anchor tags embedded in Markdown content

---

app/mailers/invite_mailer.rb
config/locales/server.en.yml
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-151

[#FLAT-151] Expose invitation email title in admin interface

---

assets/javascripts/discourse/controllers/share.js.es6
assets/javascripts/discourse/helpers/formatted-date.js.es6
assets/javascripts/discourse/templates/post-blog.hbs
assets/javascripts/discourse/templates/share.hbs
assets/javascripts/discourse/templates/topic-blog.hbs
assets/javascripts/initializers/discourse_reports.js.es6
assets/stylesheets/components/related.css.scss
assets/stylesheets/components/share.css.scss
assets/stylesheets/views/blog-post.css.scss
assets/stylesheets/views/recipes.css.scss
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-170

[#FLAT-170] Blog post layout resemble wireframe

---

assets/javascripts/discourse/templates/footer.hbs
assets/stylesheets/shared/footer.css.scss
config/locales/client.en.yml

https://sourceclear.atlassian.net/browse/FLAT-158

[flat-158] Add blogs link to footer

---

plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-184

[flat-184] Predefined blogs category

---

lib/suggested_topics_builder.rb
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-179

[#FLAT-179] Fetch only blog topics as related for blogs

---

assets/javascripts/discourse/templates/user/index.hbs
assets/stylesheets/base/form.css.scss
assets/stylesheets/views/profile.css.scss
assets/stylesheets/views/signup.css.scss

https://sourceclear.atlassian.net/browse/FLAT-176

Flat 176 change fields on profile page to text

---

app/serializers/discourse_reports/extended_user_serializer.rb
app/serializers/topic_view_serializer.rb
assets/javascripts/discourse/templates/topic-blog.hbs
config/locales/client.en.yml

https://sourceclear.atlassian.net/browse/FLAT-180

[#FLAT-180] Add username and avatar to blog page

---

app/serializers/discourse_reports/blog_serializer.rb
assets/javascripts/discourse/templates/blog.hbs

https://sourceclear.atlassian.net/browse/FLAT-188

[#FLAT-188] Cut long topic body in blogs list page

---

app/serializers/discourse_reports/extended_user_serializer.rb
assets/javascripts/discourse/templates/topic-blog.hbs

https://sourceclear.atlassian.net/browse/FLAT-185

[#FLAT-185] Additional blogs by user

---

assets/stylesheets/views/landing.css.scss
config/locales/client.en.yml

https://sourceclear.atlassian.net/browse/FLAT-192

[flat-192] Change the wording on the home page

---

assets/javascripts/discourse/templates/blogs.hbs
assets/javascripts/discourse/templates/user/blogs.hbs
assets/javascripts/discourse/templates/user/recipes.hbs

https://sourceclear.atlassian.net/browse/FLAT-189

[flat-189] Move 'Submit Blog' and 'Submit Recipe' buttons to the right

---

assets/javascripts/discourse/routes/recipes.js.es6

https://sourceclear.atlassian.net/browse/FLAT-203

[#FLAT-203] Close recipes route

---

app/serializers/discourse_reports/extended_user_serializer.rb
app/serializers/topic_view_serializer.rb
assets/javascripts/discourse/templates/post-recipe.hbs
assets/javascripts/discourse/templates/topic-blog.hbs
assets/javascripts/discourse/templates/topic-recipe.hbs

https://sourceclear.atlassian.net/browse/FLAT-198

[#FLAT-198] move author profile info to the top right in recipes

---

app/models/site_setting.rb
assets/javascripts/admin/components/site-setting.js.es6
assets/javascripts/admin/initializer.js
assets/javascripts/admin/templates/site-settings/textarea.hbs
assets/javascripts/discourse/routes/recipes-new.js.es6
assets/stylesheets/admin/base.css.scss
config/locales/server.en.yml
config/settings.yml
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-202

[#FLAT-202] Make recipe annotation default setting as textarea field

---

plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-205

[#FLAT-205] Create predefined categories

---

assets/stylesheets/admin/settings.css.scss
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-206

Fix settings buttons position [FLAT-206]

---

assets/javascripts/discourse/templates/topic-blog.hbs
assets/javascripts/discourse/templates/topic-recipe.hbs

https://sourceclear.atlassian.net/browse/FLAT-208

[#FLAT-208] Fix system avatar on recipe and blog pages

---

app/query_objects/discourse_reports/paginated_query.rb
assets/javascripts/discourse/controllers/taxonomy.js.es6

https://sourceclear.atlassian.net/browse/FLAT-212

[#FLAT-212] Fix scroll bug and infinite loading in taxonomies

---

assets/javascripts/discourse/templates/header.hbs
assets/javascripts/discourse/templates/homepage.hbs
assets/stylesheets/shared/header.css.scss
assets/stylesheets/views/landing.css.scss
config/locales/client.en.yml

https://sourceclear.atlassian.net/browse/FLAT-213

Flat 213 homepage redesign

---

app/controllers/discourse_reports/sections_controller.rb
app/models/topic.rb
app/serializers/discourse_reports/chapter_serializer.rb
app/serializers/discourse_reports/section_serializer.rb
app/serializers/topic_view_serializer.rb
app/services/discourse_reports/generate_table_content.rb
assets/javascripts/admin/controllers/admin-section.js.es6
assets/javascripts/admin/models/section.js.es6
assets/javascripts/admin/templates/toc.hbs
assets/javascripts/discourse/controllers/composer.js.es6
assets/javascripts/discourse/models/composer.js.es6
assets/javascripts/discourse/templates/composer.hbs
assets/javascripts/initializers/composer-fields.js.es6
assets/stylesheets/admin/toc.css.scss
assets/stylesheets/components/sections.css.scss
config/routes.rb
db/migrate/20150421181140_add_parent_topic_to_topics.rb
lib/post_revisor.rb

https://sourceclear.atlassian.net/browse/FLAT-209

[#FLAT-209] Sub sections navigation

---

assets/javascripts/discourse/controllers/discovery.js.es6
assets/javascripts/discourse/routes/discovery.js.es6
assets/javascripts/discourse/templates/discovery.hbs
assets/javascripts/discourse/templates/homepage.hbs
assets/javascripts/initializers/discourse_reports.js.es6
assets/stylesheets/base/base.css.scss
assets/stylesheets/views/landing.css.scss
plugin.rb

* Fix section nav position
* Fix landing section height
* Remove empty list in the discovery template

Fix homepage design

---

assets/stylesheets/components/sections.css.scss

**Task**: https://sourceclear.atlassian.net/browse/FLAT-227
Screen
---

Fix chapter heading aligned

---

assets/javascripts/discourse/routes/application.js.es6

https://sourceclear.atlassian.net/browse/FLAT-230

[#FLAT-230] Fix login help popup message

---

assets/javascripts/discourse/routes/about.js.es6
assets/javascripts/initializers/discourse_reports.js.es6
config/locales/server.en.yml
config/settings.yml
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-237

[#FLAT-237] Add link to about page in admin interface

---

lib/discourse_reports/part_chapter_topic_constraint.rb

https://sourceclear.atlassian.net/browse/FLAT-237

[#FLAT-237] Fix tags loading error

---

app/controllers/discourse_reports/table_contents_controller.rb
assets/javascripts/discourse/routes/about.js.es6
assets/javascripts/discourse/routes/table-of-contents.js.es6
config/locales/server.en.yml
config/settings.yml
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-240

[#FLAT-240] Fix back button for toc and about pages

---

assets/stylesheets/shared/navigation.css.scss

https://sourceclear.atlassian.net/browse/FLAT-218

[#FLAT-218] Rename discussion categories

---

app/controllers/discourse_reports/table_contents_controller.rb
app/services/discourse_reports/generate_table_content.rb

https://sourceclear.atlassian.net/browse/FLAT-244

[#FLAT-244] Add alphabetic order for sections in taxonomy chapter

---

app/services/discourse_reports/generate_table_content.rb
assets/stylesheets/views/toc.css.scss

https://sourceclear.atlassian.net/browse/FLAT-245

[#FLAT-245] Remove extra html elements after TOC rebuild

---

assets/javascripts/discourse/templates/topic-how-to.hbs
assets/stylesheets/shared/navigation.css.scss
assets/stylesheets/views/howto.css.scss
assets/stylesheets/views/toc.css.scss
plugin.rb

**Task**: https://sourceclear.atlassian.net/browse/FLAT-251
Screen
---

Markup of new howto page

---

app/models/site_setting.rb
config/settings.yml
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-259

[#FLAT-259] Remove site setting witch broke admin interface

---

app/controllers/discourse_reports/homepages_controller.rb
lib/archetype.rb

task: https://sourceclear.atlassian.net/browse/FLAT-254

Homepage top topics fetching

---

config/locales/server.en.yml
lib/search.rb
plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-247

[#FLAT-247] Add ability to search topic by tags

---

app/controllers/discourse_reports/table_contents_controller.rb
assets/javascripts/discourse/routes/blogs.js.es6
assets/javascripts/discourse/routes/howtos.js.es6

https://sourceclear.atlassian.net/browse/FLAT-263

[#FLAT-263] Redirect to login page for unauthorized user

---

assets/stylesheets/shared/navigation.css.scss

Update font size and toggler height

---

assets/javascripts/discourse/views/topic.js.es6
assets/javascripts/initializers/expand-topic-links.js.es6

https://sourceclear.atlassian.net/browse/FLAT-248

Move expand collapse for TOC to initializer

---

assets/javascripts/discourse/controllers/howtos.js.es6
assets/javascripts/discourse/templates/howtos.hbs
assets/javascripts/discourse/views/howtos.js.es6
lib/search.rb

https://sourceclear.atlassian.net/browse/FLAT-266

[#FLAT-266] Howtos search bug

---

assets/javascripts/discourse/templates/footer.hbs
assets/javascripts/discourse/templates/header.hbs

https://sourceclear.atlassian.net/browse/FLAT-276
https://sourceclear.atlassian.net/browse/FLAT-280

[flat-276, flat-280] Header and footer updates

---

plugin.rb

https://sourceclear.atlassian.net/browse/FLAT-287

[#FLAT-287] Fix: site settings replaced after Discourse relaunch

---

app/serializers/current_user_serializer.rb
assets/javascripts/discourse/controllers/user-blogs.js.es6
assets/javascripts/discourse/controllers/user-how-tos.js.es6
assets/javascripts/discourse/controllers/user.js.es6
assets/javascripts/discourse/templates/user/blogs.hbs
assets/javascripts/discourse/templates/user/how-tos.hbs

https://sourceclear.atlassian.net/browse/FLAT-288

[#FLAT-288] Deny access to blogs and how-tos for users by security policy

---

app/controllers/discourse_reports/homepages_controller.rb
assets/javascripts/discourse/templates/header.hbs
assets/javascripts/discourse/templates/homepage.hbs
config/locales/client.en.yml

https://sourceclear.atlassian.net/browse/FLAT-293

[#FLAT-293] Change discussions defaults from top to latest
